;;; -*- mode: Lisp; Syntax: Common-Lisp; -*-
;;;
;;; Copyright (c) 2009 by the authors.
;;;
;;; See LICENCE for details.

(in-package :hu.dwim.meta-model)

(def localization en
  (authenticated-session.web-application "application")
  (class-name.authenticated-session "session")
  (class-name.authentication-instrument "authentiucation instrument")
  (class-name.binary-relationship "binary relationship")
  (class-name.binary-relationship-end "binary relationship end")
  (class-name.message-queue "message queue")
  (class-name.n-ary-relationship "n-ary relationship")
  (class-name.n-ary-relationship-end "n-ary relationship end")
  (class-name.persistent-message "persistent message")
  (class-name.persistent-process "persistent process")
  (class-name.relationship "relationship")
  (class-name.relationship-element "relationship element")
  (class-name.relationship-end "relationship end")
  (class-name.subject "subject")
  (class-name.technical-subject "technical subject")
  (class-name.wait-for-message "wait for message")
  (class-name.wait-for-subject "wait for subject")
  (class-name.wait-for-timestamp "wait for timestamp")
  (class-name.wait-reason "wait reason")
  (process-state.broken "broken")
  (process-state.cancelled "cancelled")
  (process-state.failed "failed")
  (process-state.finished "finished")
  (process-state.in-progress "in progress")
  (process-state.initializing "initializing")
  (process-state.paused "paused")
  (process-state.running "running")
  (slot-name.authenticated-sessions "sessions")
  (slot-name.authenticated-subject "authenticated subject")
  (slot-name.authentication-instruments "authenticated instruments")
  (slot-name.description "description")
  (slot-name.documentation "documentation")
  (slot-name.editable "editable")
  (slot-name.effective-sessions "effective sessions")
  (slot-name.effective-subject "effective subject")
  (slot-name.http-user-agent "http agent")
  (slot-name.login-at "login at")
  (slot-name.login-disabled "login disabled")
  (slot-name.logout-at "logout at")
  (slot-name.name "name")
  (slot-name.process-state "process state")
  (slot-name.remote-ip-address "remote IP address")
  (slot-name.required "required")
  (slot-name.status "status")
  (slot-name.subject "subject")
  (slot-name.type "type")
  (slot-name.unique "unique")
  (slot-name.web-session-id "web session ID")
  (status.alive "alive")
  (status.crashed "crashed")
  (status.expired "expired")
  (status.logged-out "logged out")
  (status.shutdown "shutdown")
  (type-name.boolean "boolean")
  (type-name.date "date")
  (type-name.email-address "email address")
  (type-name.integer "integer")
  (type-name.integer-16 "16 bits integer")
  (type-name.integer-32 "32 bits integer")
  (type-name.integer-64 "64 bits integer")
  (type-name.ip-address "IP address")
  (type-name.member "member type")
  (type-name.number "number")
  (type-name.phone-number "phone number")
  (type-name.serialized "serialized")
  (type-name.standard-text "standard text")
  (type-name.symbol "symbol")
  (type-name.t "anything")
  (type-name.text "text")
  (type-name.time "time")
  (type-name.timestamp "timestamp")
  (type-name.url-text "URL"))
